name: App Deployment
run-name: Flask App Deployment 🚀
on: [push]
jobs:
  Build_and_Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
            python-verion: '3.9'
      - name: Display Python version
        run: python3 -c "import sys; print(sys.version)"
      - name: Setup & Dependencies
        run: |
            python3 -m venv test3
            source test3/bin/activate
            pip install pip --upgrade
            pip install -r requirements.txt
            export FLASK_APP=application
#       - name: Test
#       - run: |
#             source test3/bin/activate
#             py.test --verbose --junit-xml test-reports/results.xml

# steps:
#     - name: Clean up
#       - shell: bash
#       run: |
#         ps aux | grep -i "gunicorn" > pid.txt || exit 0
#         if [ -s pid.txt ]; then
#           kill $(cat pid.txt) 
#         fi

#   Clean:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - run: |

#   Delpoy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - run: |
#             pip install -r requirements.txt
#             pip install gunicorn
#             python3 -m gunicorn -w 4 application:app -b 0.0.0.0 --daemon
