name: App Deployment
run-name: Flask App Deployment 🚀
on: [push, workflow_dispatch]
jobs:
  Build_and_Test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
            python-version: '3.9'
      - name: Display Python version
        run: python3 -c "import sys; print(sys.version)"
      - name: Setup & Dependencies
        run: |
            python3 -m venv test3
            source test3/bin/activate
            pip install pip --upgrade
            pip install -r requirements.txt
            export FLASK_APP=application
      - name: Test with pytest
        run: |
            source test3/bin/activate
            py.test --verbose --junit-xml test-reports/results.xml

#   Clean:
#     runs-on: self-hosted
#     steps:
#       - uses: actions/checkout@v4
#       - name: Stopping gunicorn process
#         run: |
#             if [[ $(ps aux | grep -i "gunicorn" | tr -s " " | head -n 1 | cut -d " " -f 2) != 0 ]]; 
#             then
#                 ps aux | grep -i "gunicorn" | tr -s " " | head -n 1 | cut -d " " -f 2 > pid.txt
#                 kill $(cat pid.txt)
#                 exit 0
#             fi

  Deploy:
    runs-on: self-hosted
    needs: Build_and_Test
    steps:
      - uses: actions/checkout@v4
      - name: Deploy app
        run: |
            # pip install -r requirements.txt
            # pip install gunicorn
            python3 -m gunicorn -w 4 application:app -b 0.0.0.0 --daemon
            
